#!/bin/bash

m_path="$1" #Directory
m_name="$2" #Name
m_cat="$3" #Category
m_fpath="$4" #Full Path


#IFS='
#'

function convert_file () {

for i in *;
do

file_ext="${i##*.}" 

if [ ! -d "$i" ] 
then

if [[ $file_ext == "avi" ]] || [[ $file_ext == "mkv" ]] || [[ $file_ext == "wmv" ]] || [[ $file_ext == "flv" ]] || [[ $file_ext == "mov" ]] 
then
        ffmpeg -i "$i" -codec copy "${i%.*}.mp4"
        while pidof /usr/bin/ffmpeg; do sleep 10; done >/dev/null #sleep until movie is processed
        chmod 777 "${i%.*}.mp4"
        mv "${i%.*}.mp4" "/media/mdrive/$m_cat"
        rm "$i"
       
elif [ $file_ext == "srt" ]
then #rename to movie name and move to category
mv "$i" "/media/mdrive/$m_cat/$m_name.srt"

elif [ $file_ext == "mp4" ] 
then #move mp4 to category without conversion
mv "$i" "/media/mdrive/$m_cat"

else
rm "$i" #delete if anything other than above
fi

fi

done


}

###############END FUNCTION#####################

if [ -d "$m_fpath" ] 
then #if folder for video exists
cd "$m_fpath"
convert_file 

else #else if no parent folder exists
cd "$m_path"
convert_file
fi


read -p "Press [enter] key to exit..."
